// Demo catalogue used when Google Sheets is not connected yet.
// Images live in /public/images so the client demo looks complete without Drive.
import { Product, Category, SiteSettings, GalleryItem, Testimonial } from '../models';

const now = new Date().toISOString();

function product(p: Partial<Product> & { id: string; name: string; category: string }): Product {
  return {
    product_code: `SKWC-${p.id.padStart(3, '0')}`,
    slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/g, ''),
    description:
      'Hand-finished from our curated wedding collection — visit the store for a personal trial and styling session.',
    short_description: 'Curated wedding piece. Store visit recommended for trial.',
    rental_available: false,
    purchase_available: true,
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: ['Maroon', 'Gold', 'Ivory'],
    material: 'Silk blend',
    fabric: 'Silk',
    occasion: ['Wedding'],
    tags: ['bridal'],
    gallery_images: [],
    featured: false,
    new_arrival: false,
    sale: false,
    status: 'active',
    created_at: now,
    updated_at: now,
    ...p,
  } as Product;
}

export const demoProducts: Product[] = [
  product({
    id: '1',
    name: 'Royal Maroon Bridal Lehenga',
    category: 'bridal-lehengas',
    price: 45000,
    main_image: '/images/lehenga-maroon.jpg',
    gallery_images: ['/images/lehenga-maroon.jpg', '/images/hero.jpg', '/images/necklace.jpg'],
    featured: true,
    new_arrival: true,
    occasion: ['Bridal', 'Wedding'],
  }),
  product({
    id: '2',
    name: 'Champagne Gold Reception Gown',
    category: 'reception-wear',
    price: 38000,
    main_image: '/images/lehenga-gold.jpg',
    gallery_images: ['/images/lehenga-gold.jpg', '/images/tikka.jpg'],
    featured: true,
    occasion: ['Reception'],
    colors: ['Champagne', 'Gold'],
  }),
  product({
    id: '3',
    name: 'Emerald Sangeet Lehenga',
    category: 'sangeet-wear',
    price: 32000,
    sale_price: 27000,
    sale: true,
    main_image: '/images/lehenga-green.jpg',
    gallery_images: ['/images/lehenga-green.jpg'],
    occasion: ['Sangeet'],
    colors: ['Emerald', 'Gold'],
  }),
  product({
    id: '4',
    name: 'Ivory Engagement Gown',
    category: 'engagement-wear',
    price: 41000,
    main_image: '/images/gown-ivory.jpg',
    gallery_images: ['/images/gown-ivory.jpg', '/images/earrings.jpg'],
    new_arrival: true,
    occasion: ['Engagement'],
    colors: ['Ivory', 'Pearl'],
  }),
  product({
    id: '5',
    name: 'Blush Mehendi Anarkali',
    category: 'mehendi-wear',
    price: 22000,
    main_image: '/images/anarkali.jpg',
    gallery_images: ['/images/anarkali.jpg'],
    occasion: ['Mehendi'],
    colors: ['Blush', 'Gold'],
    fabric: 'Georgette',
  }),
  product({
    id: '6',
    name: 'Wine Party Wear Gown',
    category: 'party-wear',
    price: 18000,
    main_image: '/images/party-wear.jpg',
    gallery_images: ['/images/party-wear.jpg'],
    occasion: ['Party'],
    colors: ['Wine'],
  }),
  product({
    id: '7',
    name: 'Classic Bridal Kundan Necklace Set',
    category: 'bridal-jewellery',
    subcategory: 'necklace-sets',
    price: 65000,
    main_image: '/images/bridal-jewellery-set.jpg',
    gallery_images: ['/images/bridal-jewellery-set.jpg', '/images/necklace.jpg', '/images/tikka.jpg'],
    featured: true,
    occasion: ['Bridal'],
    material: 'Kundan',
    fabric: '',
    sizes: [],
    colors: ['Gold'],
  }),
  product({
    id: '8',
    name: 'Polki Maang Tikka',
    category: 'jewellery',
    subcategory: 'maang-tikka',
    price: 12000,
    main_image: '/images/tikka.jpg',
    gallery_images: ['/images/tikka.jpg'],
    material: 'Polki',
    fabric: '',
    sizes: [],
    colors: ['Gold'],
  }),
  product({
    id: '9',
    name: 'Temple Jhumka Earrings',
    category: 'jewellery',
    subcategory: 'earrings',
    price: 9500,
    main_image: '/images/earrings.jpg',
    gallery_images: ['/images/earrings.jpg'],
    new_arrival: true,
    material: 'Temple gold plated',
    fabric: '',
    sizes: [],
    colors: ['Gold', 'Ruby'],
  }),
  product({
    id: '10',
    name: 'Gold Plated Bridal Bangles Set',
    category: 'jewellery',
    subcategory: 'bangles',
    price: 15000,
    main_image: '/images/bangles.jpg',
    gallery_images: ['/images/bangles.jpg'],
    material: 'Gold plated',
    fabric: '',
    sizes: ['2.4', '2.6', '2.8'],
    colors: ['Gold'],
  }),
  product({
    id: '11',
    name: 'Designer Rental Lehenga — Rose Pink',
    category: 'rental',
    price: 0,
    rental_price: 6500,
    rental_available: true,
    purchase_available: false,
    main_image: '/images/rental.jpg',
    gallery_images: ['/images/rental.jpg', '/images/anarkali.jpg'],
    occasion: ['Wedding', 'Reception'],
    colors: ['Rose Pink'],
  }),
  product({
    id: '12',
    name: 'Peacock Blue Wedding Wear — Sale',
    category: 'sale',
    price: 29000,
    sale_price: 19999,
    sale: true,
    main_image: '/images/sale.jpg',
    gallery_images: ['/images/sale.jpg'],
    occasion: ['Wedding'],
    colors: ['Peacock Blue'],
  }),
  product({
    id: '13',
    name: 'Embroidered Bridal Potli',
    category: 'potli',
    price: 2800,
    main_image: '/images/potli.jpg',
    gallery_images: ['/images/potli.jpg'],
    featured: true,
    new_arrival: true,
    occasion: ['Bridal', 'Wedding'],
    colors: ['Maroon', 'Gold'],
    fabric: 'Silk',
    sizes: [],
    tags: ['potli', 'trousseau'],
    short_description: 'Hand-finished potli to complete the bridal carry look.',
  }),
  product({
    id: '14',
    name: 'Gold-Plated Kaleere Pair',
    category: 'kaleere',
    price: 4500,
    main_image: '/images/kaleere.jpg',
    gallery_images: ['/images/kaleere.jpg'],
    featured: true,
    occasion: ['Bridal'],
    colors: ['Gold'],
    material: 'Gold plated',
    fabric: '',
    sizes: [],
    tags: ['kaleere', 'bridal'],
  }),
  product({
    id: '15',
    name: 'Embellished Bridal Dupatta',
    category: 'dupatta',
    price: 8500,
    main_image: '/images/dupatta.jpg',
    gallery_images: ['/images/dupatta.jpg'],
    occasion: ['Bridal', 'Reception'],
    colors: ['Ivory', 'Gold'],
    fabric: 'Net',
    sizes: [],
    tags: ['dupatta'],
  }),
  product({
    id: '16',
    name: 'Designer Blouse — Zari Work',
    category: 'designer-blouse',
    price: 7200,
    main_image: '/images/designer-blouse.jpg',
    gallery_images: ['/images/designer-blouse.jpg'],
    new_arrival: true,
    occasion: ['Wedding', 'Sangeet'],
    colors: ['Maroon', 'Gold'],
    fabric: 'Silk',
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    tags: ['blouse'],
  }),
  product({
    id: '17',
    name: 'Reversible Stone Necklace Set',
    category: 'reversible-stone-jewellery',
    price: 18500,
    main_image: '/images/reversible-stone.jpg',
    gallery_images: ['/images/reversible-stone.jpg'],
    featured: true,
    occasion: ['Wedding', 'Reception'],
    colors: ['Gold', 'Multi'],
    material: 'Reversible stone',
    fabric: '',
    sizes: [],
    tags: ['jewellery'],
  }),
  product({
    id: '18',
    name: 'Antique Temple Necklace — Gold Look',
    category: 'antique-temple-jewellery',
    price: 22000,
    main_image: '/images/antique-temple.jpg',
    gallery_images: ['/images/antique-temple.jpg'],
    featured: true,
    occasion: ['Bridal', 'Wedding'],
    colors: ['Antique Gold'],
    material: 'Temple gold look',
    fabric: '',
    sizes: [],
    tags: ['antique', 'temple'],
  }),
  product({
    id: '19',
    name: 'American Diamond Choker Set',
    category: 'american-diamond-jewellery',
    price: 9800,
    main_image: '/images/american-diamond.jpg',
    gallery_images: ['/images/american-diamond.jpg'],
    new_arrival: true,
    occasion: ['Reception', 'Party'],
    colors: ['Silver', 'White'],
    material: 'American diamond',
    fabric: '',
    sizes: [],
    tags: ['ad', 'jewellery'],
  }),
  product({
    id: '20',
    name: 'Classic Nath — Nose Ring',
    category: 'nose-ring',
    price: 2400,
    main_image: '/images/nose-ring.jpg',
    gallery_images: ['/images/nose-ring.jpg'],
    occasion: ['Bridal'],
    colors: ['Gold'],
    material: 'Gold plated',
    fabric: '',
    sizes: [],
    tags: ['nath', 'nose-ring'],
  }),
  product({
    id: '21',
    name: 'Polki Cocktail Ring',
    category: 'rings',
    price: 3600,
    main_image: '/images/rings.jpg',
    gallery_images: ['/images/rings.jpg'],
    occasion: ['Engagement', 'Bridal'],
    colors: ['Gold'],
    material: 'Polki',
    fabric: '',
    sizes: ['Adjustable'],
    tags: ['rings'],
  }),
  product({
    id: '22',
    name: 'Kundan Bracelet Pair',
    category: 'bracelets',
    price: 5400,
    main_image: '/images/bracelets.jpg',
    gallery_images: ['/images/bracelets.jpg'],
    occasion: ['Wedding', 'Sangeet'],
    colors: ['Gold'],
    material: 'Kundan',
    fabric: '',
    sizes: [],
    tags: ['bracelets'],
  }),
  product({
    id: '23',
    name: 'Crop Top & Skirt — Festive Set',
    category: 'crop-tops-skirts',
    price: 16500,
    main_image: '/images/crop-top-skirt.jpg',
    gallery_images: ['/images/crop-top-skirt.jpg'],
    new_arrival: true,
    occasion: ['Sangeet', 'Mehendi', 'Party'],
    colors: ['Wine', 'Gold'],
    fabric: 'Georgette',
    tags: ['crop-top', 'skirt'],
  }),
];

export const demoCategories: Category[] = [
  { id: '1', name: 'Bridal Lehengas', slug: 'bridal-lehengas', image: '/images/lehenga-maroon.jpg', status: 'active', display_order: 1 },
  { id: '2', name: 'Wedding Wear', slug: 'wedding-wear', image: '/images/gown-ivory.jpg', status: 'active', display_order: 2 },
  { id: '3', name: 'Party Wear', slug: 'party-wear', image: '/images/party-wear.jpg', status: 'active', display_order: 3 },
  { id: '4', name: 'Jewellery', slug: 'jewellery', image: '/images/necklace.jpg', status: 'active', display_order: 4 },
  { id: '5', name: 'Bridal Jewellery', slug: 'bridal-jewellery', image: '/images/bridal-jewellery-set.jpg', status: 'active', display_order: 5 },
  { id: '6', name: 'Rental Collection', slug: 'rental', image: '/images/rental.jpg', status: 'active', display_order: 6 },
  { id: '7', name: 'Sale Collection', slug: 'sale', image: '/images/sale.jpg', status: 'active', display_order: 7 },
  { id: '8', name: 'Potli', slug: 'potli', description: 'Embroidered bridal potlis to finish the carry look.', image: '/images/potli.jpg', status: 'active', display_order: 8 },
  { id: '9', name: 'Kaleere', slug: 'kaleere', description: 'Traditional kaleere for the bridal ceremony.', image: '/images/kaleere.jpg', status: 'active', display_order: 9 },
  { id: '10', name: 'Dupatta', slug: 'dupatta', description: 'Embellished dupattas for pheras and portraits.', image: '/images/dupatta.jpg', status: 'active', display_order: 10 },
  { id: '11', name: 'Designer Blouse', slug: 'designer-blouse', description: 'Zari and embroidered blouses, including custom sizing.', image: '/images/designer-blouse.jpg', status: 'active', display_order: 11 },
  { id: '12', name: 'Reversible Stone Jewellery', slug: 'reversible-stone-jewellery', description: 'Two looks in one — stone sets for wedding and reception.', image: '/images/reversible-stone.jpg', status: 'active', display_order: 12 },
  { id: '13', name: 'Antique Temple Jewellery', slug: 'antique-temple-jewellery', description: 'Gold-look temple jewellery with an heirloom finish.', image: '/images/antique-temple.jpg', status: 'active', display_order: 13 },
  { id: '14', name: 'American Diamond Jewellery', slug: 'american-diamond-jewellery', description: 'American diamond chokers, sets and festive sparkle.', image: '/images/american-diamond.jpg', status: 'active', display_order: 14 },
  { id: '15', name: 'Nose Ring', slug: 'nose-ring', description: 'Bridal nath and nose rings for the complete look.', image: '/images/nose-ring.jpg', status: 'active', display_order: 15 },
  { id: '16', name: 'Rings', slug: 'rings', description: 'Polki, kundan and cocktail rings.', image: '/images/rings.jpg', status: 'active', display_order: 16 },
  { id: '17', name: 'Bracelets', slug: 'bracelets', description: 'Kundan and festive bracelets to pair with bangles.', image: '/images/bracelets.jpg', status: 'active', display_order: 17 },
  { id: '18', name: 'Crop Tops & Skirts', slug: 'crop-tops-skirts', description: 'Festive crop tops and skirts for sangeet and mehendi.', image: '/images/crop-top-skirt.jpg', status: 'active', display_order: 18 },
];

const EXTRA_SLUGS = new Set([
  'potli',
  'kaleere',
  'dupatta',
  'designer-blouse',
  'reversible-stone-jewellery',
  'antique-temple-jewellery',
  'american-diamond-jewellery',
  'nose-ring',
  'rings',
  'bracelets',
  'crop-tops-skirts',
]);

export function mergeCatalogueCategories(existing: Category[]): Category[] {
  const slugs = new Set(existing.map((c) => c.slug));
  const missing = demoCategories.filter((c) => EXTRA_SLUGS.has(c.slug) && !slugs.has(c.slug));
  return [...existing, ...missing].sort((a, b) => a.display_order - b.display_order);
}

export function mergeCatalogueProducts(existing: Product[]): Product[] {
  const cats = new Set(existing.map((p) => p.category));
  const missing = demoProducts.filter((p) => EXTRA_SLUGS.has(p.category) && !cats.has(p.category));
  return [...existing, ...missing];
}

export const demoGallery: GalleryItem[] = [
  { id: '1', title: 'Royal Maroon Bridal', category: 'Bridal', image_url: '/images/hero.jpg', display_order: 1, status: 'active' },
  { id: '2', title: 'Champagne Reception', category: 'Wedding Looks', image_url: '/images/lehenga-gold.jpg', display_order: 2, status: 'active' },
  { id: '3', title: 'Emerald Sangeet', category: 'Collections', image_url: '/images/lehenga-green.jpg', display_order: 3, status: 'active' },
  { id: '4', title: 'Ivory Engagement', category: 'Bridal', image_url: '/images/gown-ivory.jpg', display_order: 4, status: 'active' },
  { id: '5', title: 'Kundan Necklace', category: 'Jewellery', image_url: '/images/necklace.jpg', display_order: 5, status: 'active' },
  { id: '6', title: 'Temple Jhumkas', category: 'Jewellery', image_url: '/images/earrings.jpg', display_order: 6, status: 'active' },
  { id: '7', title: 'Bridal Bangles', category: 'Jewellery', image_url: '/images/bangles.jpg', display_order: 7, status: 'active' },
  { id: '8', title: 'Rose Pink Rental', category: 'Collections', image_url: '/images/rental.jpg', display_order: 8, status: 'active' },
];

export const demoTestimonials: Testimonial[] = [
  // {
  //   id: '1',
  //   customer_name: 'Vanshika Agnihotri',
  //   testimonial:
  //     'I took my engagement outfit from here, and it was so amazing. The look felt special from the moment I tried it on.',
  //   rating: 5,
  //   status: 'active',
  //   display_order: 1,
  // },
  {
    id: '2',
    customer_name: 'Ruchi Sengar',
    testimonial:
      'I loved the lehenga. The quality is awesome and the service is also amazing — exactly what I wanted for my wedding look.',
    rating: 5,
    status: 'active',
    display_order: 2,
  },
  // {
  //   id: '3',
  //   customer_name: 'Payal Talreja',
  //   testimonial:
  //     'Awesome collection and affordable prices. Beautiful pieces without feeling overpriced.',
  //   rating: 5,
  //   status: 'active',
  //   display_order: 3,
  // },
  {
    id: '4',
    customer_name: 'Richa Khandelwal',
    testimonial: 'Best collections in Gwalior. The bridal range is stunning — truly worth the visit.',
    rating: 5,
    status: 'active',
    display_order: 4,
  },
  {
    id: '5',
    customer_name: 'Soniya Chaudhary',
    testimonial: 'Beautiful bridal collection. Every piece felt festive, elegant and ready for the big day.',
    rating: 5,
    status: 'active',
    display_order: 5,
  },
];

export const demoSettings: SiteSettings = {
  business_name: 'Shri Krishna Wedding Collection',
  phone: '+91 83195 58820',
  whatsapp_number: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '9183195 58820',
  email: 'shrikrishna2110@gmail.com',
  address: 'Dana Oli, New sarafa Dana Oli, Daulat Ganj, Gwalior, Madhya Pradesh 474001',
  google_maps_url: 'https://maps.app.goo.gl/QN4tTkbjddrdBZvy5',
  business_hours: '11:00 AM – 9:00 PM',
  instagram_url: '',
  facebook_url: '',
  linkedin_url: '',
  google_url: '',
  homepage_headline: 'Where Every Wedding Dream Finds Its Perfect Look',
  homepage_subtitle:
    'Discover exquisite bridal lehengas, wedding couture and timeless jewellery curated for your most unforgettable celebrations.',
};
