// Demo catalogue used when Google Sheets is not connected yet.
// Images live in /public/images so the client demo looks complete without Drive.
import { Product, Category, SiteSettings, GalleryItem, Testimonial } from '../models';

const now = new Date().toISOString();

function product(p: Partial<Product> & { id: string; name: string; category: string }): Product {
  return {
    product_code: `SKWC-${p.id.padStart(3, '0')}`,
    slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/g, ''),
    description:
      'Hand-finished from our curated wedding collection — visit the store for a personal trial and styling session.',
    short_description: 'Curated wedding piece. Store visit recommended for trial.',
    rental_available: false,
    purchase_available: true,
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: ['Maroon', 'Gold', 'Ivory'],
    material: 'Silk blend',
    fabric: 'Silk',
    occasion: ['Wedding'],
    tags: ['bridal'],
    gallery_images: [],
    featured: false,
    new_arrival: false,
    sale: false,
    status: 'active',
    created_at: now,
    updated_at: now,
    ...p,
  } as Product;
}

export const demoProducts: Product[] = [
  product({
    id: '1',
    name: 'Royal Maroon Bridal Lehenga',
    category: 'bridal-lehengas',
    price: 45000,
    main_image: '/images/lehenga-maroon.jpg',
    gallery_images: ['/images/lehenga-maroon.jpg', '/images/hero.jpg', '/images/necklace.jpg'],
    featured: true,
    new_arrival: true,
    occasion: ['Bridal', 'Wedding'],
  }),
  product({
    id: '2',
    name: 'Champagne Gold Reception Gown',
    category: 'reception-wear',
    price: 38000,
    main_image: '/images/lehenga-gold.jpg',
    gallery_images: ['/images/lehenga-gold.jpg', '/images/tikka.jpg'],
    featured: true,
    occasion: ['Reception'],
    colors: ['Champagne', 'Gold'],
  }),
  product({
    id: '3',
    name: 'Emerald Sangeet Lehenga',
    category: 'sangeet-wear',
    price: 32000,
    sale_price: 27000,
    sale: true,
    main_image: '/images/lehenga-green.jpg',
    gallery_images: ['/images/lehenga-green.jpg'],
    occasion: ['Sangeet'],
    colors: ['Emerald', 'Gold'],
  }),
  product({
    id: '4',
    name: 'Ivory Engagement Gown',
    category: 'engagement-wear',
    price: 41000,
    main_image: '/images/gown-ivory.jpg',
    gallery_images: ['/images/gown-ivory.jpg', '/images/earrings.jpg'],
    new_arrival: true,
    occasion: ['Engagement'],
    colors: ['Ivory', 'Pearl'],
  }),
  product({
    id: '5',
    name: 'Blush Mehendi Anarkali',
    category: 'mehendi-wear',
    price: 22000,
    main_image: '/images/anarkali.jpg',
    gallery_images: ['/images/anarkali.jpg'],
    occasion: ['Mehendi'],
    colors: ['Blush', 'Gold'],
    fabric: 'Georgette',
  }),
  product({
    id: '6',
    name: 'Wine Party Wear Gown',
    category: 'party-wear',
    price: 18000,
    main_image: '/images/party-wear.jpg',
    gallery_images: ['/images/party-wear.jpg'],
    occasion: ['Party'],
    colors: ['Wine'],
  }),
  product({
    id: '7',
    name: 'Classic Bridal Kundan Necklace Set',
    category: 'bridal-jewellery',
    subcategory: 'necklace-sets',
    price: 65000,
    main_image: '/images/necklace.jpg',
    gallery_images: ['/images/necklace.jpg', '/images/earrings.jpg', '/images/tikka.jpg'],
    featured: true,
    occasion: ['Bridal'],
    material: 'Kundan',
    fabric: '',
    sizes: [],
    colors: ['Gold'],
  }),
  product({
    id: '8',
    name: 'Polki Maang Tikka',
    category: 'jewellery',
    subcategory: 'maang-tikka',
    price: 12000,
    main_image: '/images/tikka.jpg',
    gallery_images: ['/images/tikka.jpg'],
    material: 'Polki',
    fabric: '',
    sizes: [],
    colors: ['Gold'],
  }),
  product({
    id: '9',
    name: 'Temple Jhumka Earrings',
    category: 'jewellery',
    subcategory: 'earrings',
    price: 9500,
    main_image: '/images/earrings.jpg',
    gallery_images: ['/images/earrings.jpg'],
    new_arrival: true,
    material: 'Temple gold plated',
    fabric: '',
    sizes: [],
    colors: ['Gold', 'Ruby'],
  }),
  product({
    id: '10',
    name: 'Gold Plated Bridal Bangles Set',
    category: 'jewellery',
    subcategory: 'bangles',
    price: 15000,
    main_image: '/images/bangles.jpg',
    gallery_images: ['/images/bangles.jpg'],
    material: 'Gold plated',
    fabric: '',
    sizes: ['2.4', '2.6', '2.8'],
    colors: ['Gold'],
  }),
  product({
    id: '11',
    name: 'Designer Rental Lehenga — Rose Pink',
    category: 'rental',
    price: 0,
    rental_price: 6500,
    rental_available: true,
    purchase_available: false,
    main_image: '/images/rental.jpg',
    gallery_images: ['/images/rental.jpg', '/images/anarkali.jpg'],
    occasion: ['Wedding', 'Reception'],
    colors: ['Rose Pink'],
  }),
  product({
    id: '12',
    name: 'Peacock Blue Wedding Wear — Sale',
    category: 'sale',
    price: 29000,
    sale_price: 19999,
    sale: true,
    main_image: '/images/sale.jpg',
    gallery_images: ['/images/sale.jpg'],
    occasion: ['Wedding'],
    colors: ['Peacock Blue'],
  }),
];

export const demoCategories: Category[] = [
  { id: '1', name: 'Bridal Lehengas', slug: 'bridal-lehengas', image: '/images/lehenga-maroon.jpg', status: 'active', display_order: 1 },
  { id: '2', name: 'Wedding Wear', slug: 'wedding-wear', image: '/images/gown-ivory.jpg', status: 'active', display_order: 2 },
  { id: '3', name: 'Party Wear', slug: 'party-wear', image: '/images/party-wear.jpg', status: 'active', display_order: 3 },
  { id: '4', name: 'Jewellery', slug: 'jewellery', image: '/images/necklace.jpg', status: 'active', display_order: 4 },
  { id: '5', name: 'Bridal Jewellery', slug: 'bridal-jewellery', image: '/images/tikka.jpg', status: 'active', display_order: 5 },
  { id: '6', name: 'Rental Collection', slug: 'rental', image: '/images/rental.jpg', status: 'active', display_order: 6 },
  { id: '7', name: 'Sale Collection', slug: 'sale', image: '/images/sale.jpg', status: 'active', display_order: 7 },
];

export const demoGallery: GalleryItem[] = [
  { id: '1', title: 'Royal Maroon Bridal', category: 'Bridal', image_url: '/images/hero.jpg', display_order: 1, status: 'active' },
  { id: '2', title: 'Champagne Reception', category: 'Wedding Looks', image_url: '/images/lehenga-gold.jpg', display_order: 2, status: 'active' },
  { id: '3', title: 'Emerald Sangeet', category: 'Collections', image_url: '/images/lehenga-green.jpg', display_order: 3, status: 'active' },
  { id: '4', title: 'Ivory Engagement', category: 'Bridal', image_url: '/images/gown-ivory.jpg', display_order: 4, status: 'active' },
  { id: '5', title: 'Kundan Necklace', category: 'Jewellery', image_url: '/images/necklace.jpg', display_order: 5, status: 'active' },
  { id: '6', title: 'Temple Jhumkas', category: 'Jewellery', image_url: '/images/earrings.jpg', display_order: 6, status: 'active' },
  { id: '7', title: 'Bridal Bangles', category: 'Jewellery', image_url: '/images/bangles.jpg', display_order: 7, status: 'active' },
  { id: '8', title: 'Rose Pink Rental', category: 'Collections', image_url: '/images/rental.jpg', display_order: 8, status: 'active' },
];

export const demoTestimonials: Testimonial[] = [
  {
    id: '1',
    customer_name: 'Vanshika Agnihotri',
    testimonial:
      'I took my engagement outfit from here, and it was so amazing. The look felt special from the moment I tried it on.',
    rating: 5,
    status: 'active',
    display_order: 1,
  },
  {
    id: '2',
    customer_name: 'Ruchi Sengar',
    testimonial:
      'I loved the lehenga. The quality is awesome and the service is also amazing — exactly what I wanted for my wedding look.',
    rating: 5,
    status: 'active',
    display_order: 2,
  },
  {
    id: '3',
    customer_name: 'Payal Talreja',
    testimonial:
      'Awesome collection and affordable prices. Beautiful pieces without feeling overpriced.',
    rating: 5,
    status: 'active',
    display_order: 3,
  },
  {
    id: '4',
    customer_name: 'Richa Khandelwal',
    testimonial: 'Best collections in Gwalior. The bridal range is stunning — truly worth the visit.',
    rating: 5,
    status: 'active',
    display_order: 4,
  },
  {
    id: '5',
    customer_name: 'Soniya Chaudhary',
    testimonial: 'Beautiful bridal collection. Every piece felt festive, elegant and ready for the big day.',
    rating: 5,
    status: 'active',
    display_order: 5,
  },
];

export const demoSettings: SiteSettings = {
  business_name: 'Shri Krishna Wedding Collection',
  phone: '+91 90000 00000',
  whatsapp_number: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '919000000000',
  email: 'hello@shrikrishnawedding.com',
  address: 'Showroom address — update in the SETTINGS sheet',
  google_maps_url: '',
  business_hours: '11:00 AM – 8:00 PM',
  instagram_url: '',
  facebook_url: '',
  linkedin_url: '',
  google_url: '',
  homepage_headline: 'Where Every Wedding Dream Finds Its Perfect Look',
  homepage_subtitle:
    'Discover exquisite bridal lehengas, wedding couture and timeless jewellery curated for your most unforgettable celebrations.',
};
